Feature tnw
Ramon-Carrillo/TNW-Clone pull request #2
Opened 2020-09-10 06:44 UTC by Ramon-Carrillo

Please check our work.

2020-09-10 16:54 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️

#### Hey team,  your project is looking really good, however, to accomplish as the actual page, you required to do these changes, listed below:
 
_Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, to get more knowledge and have a better project to add at your portfolio.
 
 
## [REQUIRED CHANGES]
#### Clone REQUIREMENTS 👥 (Those adjusts to make your page really look like the real one)⤵
#### Large screens
Img1 ⤵
- [x] Decrease those margins
- [x] Fix that image width (to make it more similar to the original one)
- [x] Apply a blur on the background of those images to make it easier to read the text
- [x] Remove that horizontal bar
![image](https://user-images.githubusercontent.com/56762529/92762087-a47c9d80-f368-11ea-9a3e-025417a1556a.png)
Img2 ⤵
- [x] fix that iamge size
- [x] decrease that gap betwen those images and that sections below
- [x] use sans-serif fonts
![image](https://user-images.githubusercontent.com/56762529/92762405-f1f90a80-f368-11ea-988a-25f04e957903.png)
Img3⤵
- [x] Add margin-top please.
![image](https://user-images.githubusercontent.com/56762529/92763096-954a1f80-f369-11ea-8695-406ff20266b4.png)

#### Small screens
- [x] Move that section (add info, get updates, see more) to below that Latest founding
- [x] Fix typo Lastes ➡ "Latest"
- [ ] Add margin left and right
- [ ] remove that horizontal part
![image](https://user-images.githubusercontent.com/56762529/92763657-24573780-f36a-11ea-90a4-32f2945918fa.png)

#### Good practices REQUIREMENTS (Those changes to make you code like a pro 👽)⤵
- [x] Add a descriptive and meaningful description to your pull request. For more info check [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
Tip: Describe what you guys did in this project; Like: We used CSS flexbox, float and grid; we added a sidebar, we used semantic HTML. In real world: PR Should be descriptive, so the reviewer can know what you guys are trying to change at the main project.
![image](https://user-images.githubusercontent.com/56762529/92767487-8bc2b680-f36d-11ea-8e07-ddc8d485fa50.png)

- [x] Guys, next time check up the way you write some commits, they should be descriptive so the other programmer can see exactly what you changed with that commit. [Check this link](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/)
For example, look at some of those commits⤵
![image](https://user-images.githubusercontent.com/56762529/92766651-c9730f80-f36c-11ea-8fe8-8fe3712cd0fa.png)
We can't know what did you have changed. Please improve them 💪
- [x] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
![image](https://user-images.githubusercontent.com/56762529/90803794-a914df80-e2ef-11ea-9be0-40267c665254.png)
Your HTML will be something like this: 
![image](https://user-images.githubusercontent.com/56762529/90803950-e7120380-e2ef-11ea-8221-5d5d3a13e033.png)
Apply the same logic above in **ALL** those repeated rules listed below:
![image](https://user-images.githubusercontent.com/56762529/92764374-c2e39880-f36a-11ea-9f85-84ac48873157.png)

- [x] It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */  


[OPTIONAL REQUIREMENTS]
- [ ] Add ribbons and prices
![image](https://user-images.githubusercontent.com/56762529/92762892-6a5fcb80-f369-11ea-9e2e-c3a96be0cfc9.png)
## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-09-10 16:54 UTC, kevincappuccino commented on index.html
> +						<img class="w_100"
- [ ] It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */

2020-09-10 16:54 UTC, kevincappuccino commented on index.html
> +					<!--</div>-->
- [ ] It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */

2020-09-10 16:54 UTC, kevincappuccino commented on index.html
> +						<img class="w_100"
- [ ] It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */

2020-09-10 16:54 UTC, kevincappuccino commented on index.html
> +					<!--</div>-->
- [ ] It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */

2020-09-10 16:54 UTC, kevincappuccino commented on index.html
> +						<img class="w_100"
- [ ] It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */

2020-09-10 16:54 UTC, kevincappuccino commented on index.html
> +					<!--</div>-->
- [ ] It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */

2020-09-10 16:54 UTC, kevincappuccino commented on index.html
> +						<img class="w_100"
- [ ] It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */

2020-09-10 16:54 UTC, kevincappuccino commented on index.html
> +					<div class="funding_2 d_flex f_dir w_100">
- [ ] It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */

2020-09-11 11:20 UTC, Kingobaino1 commented
- As requested, the changes have been effected. However, it was observed that after creating classes for some properties and assigning them to the HTML tags, it will not render in the page. (e.g. we created a class called cover to host the property background-size: cover, but if you assign this class to the HTML tag, it won't render in the page.)

2020-09-11 21:13 UTC, Spayco requested changes
# Changes Requested 

Hello! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

* [ ] Pull Request has a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

- [ ] The Navbar should have the links on the left side, and the search bar on the right, yours are not well placed

| Yours | Original |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/11758151/92973253-b00cb900-f47b-11ea-8928-db996125662a.png) | ![image](https://user-images.githubusercontent.com/11758151/92973239-a97e4180-f47b-11ea-94a3-19eba34d40c9.png) |

on small screens

- [ ] The yellow bar breaks

![image](https://user-images.githubusercontent.com/11758151/92973368-f6faae80-f47b-11ea-8291-f836ba6c1b3b.png)



### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-09-11 22:21 UTC, Kingobaino1 commented
**Completion of required change**
- adjusted navbar as requested
- repaired breakpoint for iPhone x

2020-09-12 02:45 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 
## Great work guys, you have made a really good job

now you can merge to master your project is approved

## Happy Coding :tophat:

2020-09-12 07:20 UTC, merged